In [71]:
import pandas as pd
df = pd.read_csv('C:/Users/lkh05/OneDrive/Documents/breast-cancer.data', header = None)

In [72]:
df.head()

,0,1,2,3,4,5,6,7,8,9
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no

In [73]:
### rename columns 

df.rename(columns={0:"Class", 1:"age", 2:"menopause", 3:"tumor-size", 4:"inv-nodes", 5:"node-caps", 6:"deg-malig", 7:"breast", 8:"breast-quad", 9:"irrad"}, inplace=True)
df

,Class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irrad
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
...,...,...,...,...,...,...,...,...,...,...
281,recurrence-events,30-39,premeno,30-34,0-2,no,2,left,left_up,no
282,recurrence-events,30-39,premeno,20-24,0-2,no,3,left,left_up,yes
283,recurrence-events,60-69,ge40,20-24,0-2,no,1,right,left_up,no
284,recurrence-events,40-49,ge40,30-34,3-5,no,3,left,left_low,no
285,recurrence-events,50-59,ge40,30-34,3-5,no,3,left,left_low,no

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Class        286 non-null    object
 1   age          286 non-null    object
 2   menopause    286 non-null    object
 3   tumor-size   286 non-null    object
 4   inv-nodes    286 non-null    object
 5   node-caps    286 non-null    object
 6   deg-malig    286 non-null    int64
 7   breast       286 non-null    object
 8   breast-quad  286 non-null    object
 9   irrad        286 non-null    object
dtypes: int64(1), object(9)
memory usage: 22.5+ KB

### Question 1:
we want to encode the age column as follows: if age is 20-29, encode as 1 if age is 30-39, encode as 2,... so on if age is 70-79, encode as 6 return a new Series called cancer['newAge'] After that, we will also encode the tumor size and inv-nodes using our own encoding functions.
Then, we will one hot encode the other columns(i.e. tumor-size and inv-nodes).

In [75]:
### return new Series called cancer['newAge']

In [76]:
def function(x):
    if x=='20-29':
        return 1
    elif x=='30-39':
        return 2
    elif x=='40-49':
        return 3
    elif x=='50-59':
        return 4
    elif x=='60-69':
        return 5
    else:
        return 6
df['newAge'] = df['age'].apply(function)

In [77]:
df.drop('age', axis=1, inplace=True)
df.head(5)

,Class,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irrad,newAge
0,no-recurrence-events,premeno,30-34,0-2,no,3,left,left_low,no,2
1,no-recurrence-events,premeno,20-24,0-2,no,2,right,right_up,no,3
2,no-recurrence-events,premeno,20-24,0-2,no,2,left,left_low,no,3
3,no-recurrence-events,ge40,15-19,0-2,no,2,right,left_up,no,5
4,no-recurrence-events,premeno,0-4,0-2,no,2,right,right_low,no,3

In [78]:
### encode the tumor size and inv-nodes

In [79]:
df['tumor-size'].unique()

array(['30-34', '20-24', '15-19', '0-4', '25-29', '50-54', '10-14',
       '40-44', '35-39', '5-9', '45-49'], dtype=object)

In [80]:
def function(y):
    if y=='0-4':
        return 0
    elif y=='5-9':
        return 1
    elif y=='10-14':
        return 2
    elif y=='15-19':
        return 3
    elif y=='20-24':
        return 4
    elif y=='25-29':
        return 5
    elif y=='30-34':
        return 6
    elif y=='35-39':
        return 7
    elif y=='40-49':
        return 8
    else:
        return 9
df['newTumor_Size'] = df['tumor-size'].apply(function)

In [81]:
df.drop('tumor-size', axis=1, inplace=True)
df.head(5)

,Class,menopause,inv-nodes,node-caps,deg-malig,breast,breast-quad,irrad,newAge,newTumor_Size
0,no-recurrence-events,premeno,0-2,no,3,left,left_low,no,2,6
1,no-recurrence-events,premeno,0-2,no,2,right,right_up,no,3,4
2,no-recurrence-events,premeno,0-2,no,2,left,left_low,no,3,4
3,no-recurrence-events,ge40,0-2,no,2,right,left_up,no,5,3
4,no-recurrence-events,premeno,0-2,no,2,right,right_low,no,3,0

In [82]:
df['inv-nodes'].unique()

array(['0-2', '6-8', '9-11', '3-5', '15-17', '12-14', '24-26'],
      dtype=object)

In [83]:
def function(z):
    if z=='0-2':
        return 0
    elif z=='3-5':
        return 1
    elif z=='6-8':
        return 2
    elif z=='9-11':
        return 3
    elif z=='12-14':
        return 4
    elif z=='15-17':
        return 5
    else:
        return 6
df['newInv_Nodes'] = df['inv-nodes'].apply(function)

In [84]:
df.drop('inv-nodes', axis=1, inplace=True)

In [85]:
df.head(5)

,Class,menopause,node-caps,deg-malig,breast,breast-quad,irrad,newAge,newTumor_Size,newInv_Nodes
0,no-recurrence-events,premeno,no,3,left,left_low,no,2,6,0
1,no-recurrence-events,premeno,no,2,right,right_up,no,3,4,0
2,no-recurrence-events,premeno,no,2,left,left_low,no,3,4,0
3,no-recurrence-events,ge40,no,2,right,left_up,no,5,3,0
4,no-recurrence-events,premeno,no,2,right,right_low,no,3,0,0

In [94]:
### one hot encode the other columns

In [92]:
df_dum = pd.get_dummies(df, columns=['menopause', 'node-caps', 'breast', 'breast-quad', 'irrad'])
df_dum.head()

,Class,deg-malig,newAge,newTumor_Size,newInv_Nodes,menopause_ge40,menopause_lt40,menopause_premeno,node-caps_?,node-caps_no,...,breast_left,breast_right,breast-quad_?,breast-quad_central,breast-quad_left_low,breast-quad_left_up,breast-quad_right_low,breast-quad_right_up,irrad_no,irrad_yes
0,no-recurrence-events,3,2,6,0,0,0,1,0,1,...,1,0,0,0,1,0,0,0,1,0
1,no-recurrence-events,2,3,4,0,0,0,1,0,1,...,0,1,0,0,0,0,0,1,1,0
2,no-recurrence-events,2,3,4,0,0,0,1,0,1,...,1,0,0,0,1,0,0,0,1,0
3,no-recurrence-events,2,5,3,0,1,0,0,0,1,...,0,1,0,0,0,1,0,0,1,0
4,no-recurrence-events,2,3,0,0,0,0,1,0,1,...,0,1,0,0,0,0,1,0,1,0

### Question 2:
Now, split the data into 70%/ 30% training and testing set, set random_state = 101

In [106]:
df_dum.Class.replace(['no-recurrence-events', 'recurrence-events'], [0, 1], inplace=True)

In [107]:
X = df_dum.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]].values
y = df_dum.iloc[:, 0].values

In [108]:
X

array([[3, 2, 6, ..., 0, 1, 0],
       [2, 3, 4, ..., 1, 1, 0],
       [2, 3, 4, ..., 0, 1, 0],
       ...,
       [1, 5, 4, ..., 0, 1, 0],
       [3, 3, 6, ..., 0, 1, 0],
       [3, 4, 6, ..., 0, 1, 0]], dtype=int64)

In [109]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [111]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 101)

### Question 3:
Now, Scale X_train and X_test using Standard Scaler

In [126]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [127]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [128]:
classifier = Sequential()
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu', input_dim = 20))
# Adding the second,third and fourth hidden layer
classifier.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu')) 
classifier.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu')) 

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [129]:
### After that, compile the ANN with adam optimizer, use accuracy as metrics and figure out the appropriate loss function.

In [123]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 50, epochs = 20)

Epoch 1/20
4/4 [==============================] - 1s 5ms/step - loss: 0.6927 - accuracy: 0.6700
Epoch 2/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6913 - accuracy: 0.7250
Epoch 3/20
4/4 [==============================] - 0s 3ms/step - loss: 0.6897 - accuracy: 0.7250
Epoch 4/20
4/4 [==============================] - 0s 3ms/step - loss: 0.6878 - accuracy: 0.7250
Epoch 5/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6852 - accuracy: 0.7250
Epoch 6/20
4/4 [==============================] - 0s 4ms/step - loss: 0.6818 - accuracy: 0.7250
Epoch 7/20
4/4 [==============================] - 0s 3ms/step - loss: 0.6774 - accuracy: 0.7250
Epoch 8/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6704 - accuracy: 0.7250
Epoch 9/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6587 - accuracy: 0.7250
Epoch 10/20
4/4 [==============================] - 0s 4ms/step - loss: 0.6435 - accuracy: 0.7250
Epoch 11/20
4/4 [==============================] - 0s 3ms/step - loss: 0.6204 - accuracy: 0.7250
Epoch 12/20
4/4 [==============================] - 0s 5ms/step - loss: 0.5893 - accuracy: 0.7250
Epoch 13/20
4/4 [==============================] - 0s 5ms/step - loss: 0.5510 - accuracy: 0.7250
Epoch 14/20
4/4 [==============================] - 0s 3ms/step - loss: 0.5249 - accuracy: 0.7250
Epoch 15/20
4/4 [==============================] - 0s 5ms/step - loss: 0.5087 - accuracy: 0.7250
Epoch 16/20
4/4 [==============================] - 0s 3ms/step - loss: 0.5014 - accuracy: 0.7250
Epoch 17/20
4/4 [==============================] - 0s 11ms/step - loss: 0.4985 - accuracy: 0.7250
Epoch 18/20
4/4 [==============================] - 0s 5ms/step - loss: 0.4919 - accuracy: 0.7250
Epoch 19/20
4/4 [==============================] - 0s 2ms/step - loss: 0.4865 - accuracy: 0.7250
Epoch 20/20
4/4 [==============================] - 0s 5ms/step - loss: 0.4817 - accuracy: 0.7250

In [124]:
y_pred_ann = classifier.predict(X_test)
y_pred_ann = (y_pred_ann > 0.5)

3/3 [==============================] - 0s 0s/step

In [125]:
from sklearn.metrics import accuracy_score

score = accuracy_score(y_test,y_pred_ann)
print(score*100)

65.11627906976744

### Question 5:
Now, make another neural network with some Dropout layer to avoid overfitting

In [141]:
# Initialising the ANN with Dropout layer
classifier2 = Sequential()
# Adding the input layer and the first hidden layer
classifier2.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu', input_dim = 20))
# Adding the second,third and fourth hidden layer
classifier2.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu')) 
classifier2.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu'))
classifier2.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu')) 
# Adding the dropout layer
classifier2.add(Dropout(0.3, input_shape=(20,)))
# Adding the output layer
classifier2.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [142]:
classifier2.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
classifier2.fit(X_train, y_train, batch_size = 50, epochs = 20)

Epoch 1/20
4/4 [==============================] - 1s 8ms/step - loss: 0.6927 - accuracy: 0.6850
Epoch 2/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6914 - accuracy: 0.7250
Epoch 3/20
4/4 [==============================] - 0s 4ms/step - loss: 0.6899 - accuracy: 0.7250
Epoch 4/20
4/4 [==============================] - 0s 4ms/step - loss: 0.6879 - accuracy: 0.7250
Epoch 5/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6858 - accuracy: 0.7250
Epoch 6/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6828 - accuracy: 0.7250
Epoch 7/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6788 - accuracy: 0.7250
Epoch 8/20
4/4 [==============================] - 0s 3ms/step - loss: 0.6735 - accuracy: 0.7250
Epoch 9/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6662 - accuracy: 0.7250
Epoch 10/20
4/4 [==============================] - 0s 6ms/step - loss: 0.6518 - accuracy: 0.7250
Epoch 11/20
4/4 [==============================] - 0s 3ms/step - loss: 0.6368 - accuracy: 0.7250
Epoch 12/20
4/4 [==============================] - 0s 3ms/step - loss: 0.6105 - accuracy: 0.7250
Epoch 13/20
4/4 [==============================] - 0s 5ms/step - loss: 0.5823 - accuracy: 0.7250
Epoch 14/20
4/4 [==============================] - 0s 5ms/step - loss: 0.5465 - accuracy: 0.7250
Epoch 15/20
4/4 [==============================] - 0s 5ms/step - loss: 0.5213 - accuracy: 0.7250
Epoch 16/20
4/4 [==============================] - 0s 5ms/step - loss: 0.5122 - accuracy: 0.7250
Epoch 17/20
4/4 [==============================] - 0s 3ms/step - loss: 0.5102 - accuracy: 0.7250
Epoch 18/20
4/4 [==============================] - 0s 5ms/step - loss: 0.5071 - accuracy: 0.7250
Epoch 19/20
4/4 [==============================] - 0s 3ms/step - loss: 0.4932 - accuracy: 0.7250
Epoch 20/20
4/4 [==============================] - 0s 5ms/step - loss: 0.4844 - accuracy: 0.7250

In [146]:
y_pred_ann2 = classifier2.predict(X_test)
y_pred_ann2 = (y_pred_ann2 > 0.5)

3/3 [==============================] - 0s 4ms/step

In [147]:
from sklearn.metrics import accuracy_score

score = accuracy_score(y_test,y_pred_ann2)
print(score*100)

65.11627906976744